### ISSUE TITLE
v0.5.0 AttributeError: 'ExifTool' object has no attribute 'get_metadata_batch' and 'get_metadata'

### ISSUE THREAD

**Issue by manuel1957** [sylikc/pyexiftool#41]
After update to 0.5.0 (Successfully installed pyexiftool-0.5.0)
I get two problems:
first one the parameter executable_ from Exiftool doesn' t exist I have to replace by executable
second one  methods 'get_metadata_batch' or 'get_metadata' doesn't exist and if I have a look at the documentation there are always here 
AttributeError: 'ExifTool' object has no attribute 'get_metadata_batch'
AttributeError:  'ExifTool' object has no attribute 'get_metadata'

Could you help?

**Comment by sylikc** [comment]
@manuel1957 the ```executable_```, yes is renamed to ```executable```

* ```ExifTool``` no longer has the ```get_metadata``` functions... it now lives in ```ExifToolHelper```, so declare with ```exiftool.ExifToolHelper```
* ```get_metadata_batch``` doesn't exist anymore, since it was largely equivalent to ```get_metadata```

So in your use case, anywhere where you used ```get_metadata```, change that to ```get_metadata()[0]``` and anywhere you used ```get_metadata_batch```, replace that with ```get_metadata```

**Comment by sylikc** [comment]
Documentation is still being updated.  It should reflect these changes soon when I get the new stuff pushed out https://github.com/sylikc/pyexiftool/issues/28#issuecomment-1056032848

**Comment by sylikc** [comment]
@manuel1957 this is the method signature for your use case.  https://sylikc.github.io/pyexiftool/reference/2-helper.html#exiftool.ExifToolHelper.get_metadata

Please let me know if you have further issues

**Comment by sylikc** [comment]
closing this issue, documentation is updated, if you have further issues, let me know!
